### ISSUE TITLE
Airport and Navaid overlay for US issue

### ISSUE THREAD

**Issue by w4gon79** [rikgale/VRSCustomLayers#27]
Hi, I just finished installing the VRSCustomLayers on my server and everything is working fine except one thing. When I click on the Airport and Navaid overlays only a small section of the US populates around Louisiana. I think this has something to do with the BoundingBoxs.txt file, but adjusting the coordinates to encompass my area (Middle Tennessee) doesn't seem to have an effect. I'm hoping you can point me in the correct direction to get this feature working for me.

Thanks
Joel

**Comment by rikgale** [comment]
Hello. The whole country (USA) does not populate due to VRS and the web browsers not being able to handle that much information all in one go. Changing the info in the boundingbox file will not work as that is a reference for myself if I need to repull the data from OpenAIP.
If you send me your state or a bounding box covering your local area I can create the necessary files when I am back at my PC
Are you using VRS in the docker container or standalone?

**Comment by w4gon79** [comment]
Thanks Richard, and pardon my ignorance. After sending the question I kept looking at the files and realized how those features work. I live in Middle Tennessee about 40 miles due south of Nashville. Will -84,33.5,-90,38 work? I'm using VRS 2.4.4 on a Win10 PC so standalone. 

Thank you for looking into this.
Joel

**Comment by w4gon79** [comment]
I was actually able to fumble my way through OpenAIP and get the files created for my area. So no need to spend any time on this Richard. 

Thanks again.
Joel

**Comment by rikgale** [comment]
Ah great!
If you are able too get me the files and the bounding box I'll add them to the project.
My email is

Mygithubusername at Hotmail dot com

Or do a PR with USAx as the file name suffix

Thanks

**Comment by w4gon79** [comment]
You bet, email sent.

Joel
